version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: titanic_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

  python-app:
    build: ./python_app
    container_name: titanic_python
    depends_on:
      - mysql
    volumes:
      - ./csv:/app/csv
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  web:
    build: ./web
    container_name: titanic_web
    depends_on:
      - mysql
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
